# html lang
language: en

# main menu navigation
menu:
  Home: /
  Hobby: /hobby
  About: /about
  GitHub: https://github.com/shaohsiung
  Twitter: /twitter

# stylesheets loaded in the <head>
stylesheets:
  - /css/leon.css

# scripts loaded in the end of the body
scripts:
  - /js/leon.js

logo:
  - ./asset/logo.JPG
